server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;  # Обслуживает любой хост

    root /data;

    location @backend {
        proxy_pass http://admin_panel:8000;
    }

    location ~* \.(?:jpg|jpeg|gif|png|ico|css|js)$ {
        log_not_found off;
        expires 90d;
    }

    location ^~ /static/ {
        alias /var/www/static/;
        expires 30d;
        log_not_found off;
    }

    location /admin {
        proxy_pass http://admin_panel:8000;
    }

    location /api/ {
        proxy_pass http://admin_panel:8000;
        add_header 'Access-Control-Allow-Origin' 'http://localhost:8080' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type' always;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://localhost:8080';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Content-Type';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    location / {
        try_files $uri @backend;
    }

    error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}