# Generated by Django 4.2.30 on 2026-09-10 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название рассылки"),
                ),
                (
                    "delivery_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push-уведомление"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Немедленно"),
                            ("delayed", "Отложенная"),
                            ("recurring", "Повторяющаяся"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Тип расписания",
                    ),
                ),
                (
                    "delay_hours",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Задержка (часов)"
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Cron-выражение",
                    ),
                ),
                (
                    "recurrence_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Описание периодичности",
                    ),
                ),
                (
                    "recipient_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Массив UUID пользователей, например: ["550e8400-e29b-41d4-a716-446655440000"]',
                        verbose_name="ID получателей (UUID)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("scheduled", "Запланирована"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push-уведомление"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Канал доставки",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Тема (email)",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Используйте переменные: {{ user.name }}, {{ user.age }} и т.д.",
                        verbose_name="Тело сообщения (HTML / текст)",
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Доступные переменные"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Шаблон сообщения",
                "verbose_name_plural": "Шаблоны сообщений",
                "db_table": "message_templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(verbose_name="ID пользователя (UUID)")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push-уведомление"),
                        ],
                        max_length=10,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Запланировано на")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "last_notification_send",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя попытка отправки"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(max_length=100, verbose_name="Cron-выражение"),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Следующий запуск"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний запуск"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="notifications.campaign",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "db_table": "notification_schedules",
            },
        ),
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Статус")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Ошибка"),
                ),
                (
                    "delivery_provider",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Провайдер"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="notifications.notification",
                        verbose_name="Уведомление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории",
                "verbose_name_plural": "История отправок",
                "db_table": "notification_history",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationContent",
            fields=[
                (
                    "content_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rendered_subject",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("rendered_body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="notifications.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "notification_contents",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notifications.notificationcontent",
                verbose_name="Контент",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="notifications.messagetemplate",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["status", "scheduled_at"],
                name="idx_notif_status_sched",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user_id"], name="idx_notif_user_id"),
        ),
    ]
