# Generated by Django 4.2.30 on 2026-09-16 04:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_send_accepted_count',
            field=models.IntegerField(default=0, verbose_name='Принято получателей'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_send_errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Ошибки последней отправки'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_send_status',
            field=models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent_to_api', 'Отправлено в notification_api'), ('api_accepted', 'Принято notification_api'), ('api_rejected', 'Отклонено notification_api'), ('failed', 'Ошибка отправки')], default='pending', max_length=20, verbose_name='Статус последней отправки'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Используется для идемпотентности при повторных отправках', unique=True, verbose_name='ID заявки в notification_api'),
        ),
        migrations.CreateModel(
            name='CampaignSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(verbose_name='ID заявки')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('accepted_count', models.IntegerField(verbose_name='Принято получателей')),
                ('rejected_count', models.IntegerField(default=0, verbose_name='Отклонено получателей')),
                ('errors', models.JSONField(default=list, verbose_name='Ошибки')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='notifications.campaign')),
            ],
            options={
                'db_table': 'campaign_send_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
