# Generated by Django 4.2.30 on 2026-09-16 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_campaign_last_send_accepted_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignsendlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Лог отправки', 'verbose_name_plural': 'Логи отправок'},
        ),
        migrations.AlterModelOptions(
            name='notificationcontent',
            options={'verbose_name': 'Контент уведомления', 'verbose_name_plural': 'Контент уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='notificationschedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='recipient_ids',
            field=models.JSONField(blank=True, default=list, help_text='Массив UUID пользователей', verbose_name='ID получателей (UUID)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID заявки в notification_api'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(verbose_name='Тело сообщения (HTML / текст)'),
        ),
    ]
