# Generated by Django 4.2.13 on 2026-09-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_campaignsendlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='current_run_request_id',
            field=models.UUIDField(
                blank=True,
                help_text='Новый UUID для каждого запуска recurring. Сохраняется при retry этого запуска.',
                null=True,
                verbose_name='ID текущего запуска'
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='next_retry_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Время следующей попытки отправки при временной ошибке API (таймаут, 5xx)',
                null=True,
                verbose_name='Следующая попытка при сбое'
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='last_send_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает отправки'),
                    ('pending_retry', 'Временный сбой, ожидает повторной попытки'),
                    ('sent_to_api', 'Отправлено в notification_api'),
                    ('api_accepted', 'Принято notification_api'),
                    ('api_rejected', 'Отклонено notification_api (ошибка данных)'),
                    ('failed', 'Ошибка отправки')
                ],
                default='pending',
                max_length=20,
                verbose_name='Статус последней отправки'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает'),
                    ('sending', 'Отправляется'),
                    ('sent', 'Отправлено'),
                    ('failed', 'Ошибка'),
                    ('skipped', 'Пропущено')
                ],
                default='pending',
                max_length=20,
                verbose_name='Статус'),
        ),
    ]
