# version: '3'

services:
  postgres-db:
    image: postgres:16
    container_name: movies_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app_net  # 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: movies_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net  # 

  etl_service:
    build: .
    container_name: movies_etl
    environment:
      PG_DSN: ${PG_DSN}
      PGOPTIONS: ${PG_DSN_OPTIONS}
      ES_DSN: ${ES_DSN}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS}
      MAX_RETRIES: ${MAX_RETRIES}
      PG_FETCH_SIZE: ${PG_FETCH_SIZE}
      ES_BULK_SIZE: ${ES_BULK_SIZE}
      ES_INDEX_NAME: ${ES_INDEX_NAME}
    volumes:
       - ./state:/app/state
    depends_on:
      postgres-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:  
    driver: bridge

volumes:
  pg_data:
  es_data:
