"""add_table_social_account

Revision ID: 60aa65d8a8a8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 22:55:36.489963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60aa65d8a8a8'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index('idx_social_accounts_provider', 'social_accounts', ['provider'], unique=False)
    op.create_index('idx_social_accounts_user_id', 'social_accounts', ['user_id'], unique=False)
    op.add_column('login_history', sa.Column('user_device_type', sa.String(length=20), nullable=False))
    op.create_index('idx_login_history_device_type', 'login_history', ['user_device_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_history_device_type', table_name='login_history')
    op.drop_column('login_history', 'user_device_type')
    op.drop_index('idx_social_accounts_user_id', table_name='social_accounts')
    op.drop_index('idx_social_accounts_provider', table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
